#On specifie le port du gateway
server:
  port: 8880
  #Le nom de l'application
spring:
  application:
    name: gateway-service
    #ici nous allons specifier les routes des micro-services
  cloud:
    #désactiver l'enregistrement parce qu'on na pas créer de discovery service
    discovery:
      enabled: true
    #gateway:
     # routes:
        #   - id: r1
          #le port du micro service
        #   uri: http://localhost:8081
        #   predicates:
            #le chemain d'accès
        #      - Path= /customers/**
        # - id: r2
        #  uri: http://localhost:8080
        #  predicates:
      #   - Path= /products/**
